# Authorize
ADMIN = "admin"
SUPER_ADMIN = "superAdmin"


# ERROR CODES
VALIDATION_GET_BY_ID_CODE = "UGBIV.0001"
VALIDATION_LOGIN_USERNAME_CODE = "ULV.0001"
VALIDATION_LOGIN_PASSWORD_CODE = "ULV.0002"
LOGIC_LOGIN_INCORRECT_INFO_CODE = "UBL.0001"
LOGIC_LOGIN_ERROR_CODE = "UBL.0002"
LOGIC_LOGIN_GET_BY_ID_CODE = "UBL.0003"
LOGIC_GET_BY_ID_ERROR_CODE = "UBGBI.0004"
LOGIC_GET_ALL_ERROR_CODE = "UBGBI.0005"
LOGIC_REGISTER_ERROR_CODE = "UBGBI.0006"
LOGIC_UPDATE_CODE = "UBGBI.0007"
LOGIC_UPDATE_ERROR_CODE = "UBGBI.0008"
LOGIC_SOFT_DELETE_CODE = "UBGBI.0009"
LOGIC_SOFT_DELETE_ERROR_CODE = "UBGBI.0010"
LOGIC_HARD_DELETE_CODE = "UBGBI.0011"
LOGIC_HARD_DELETE_ERROR_CODE = "UBGBI.0012"
